###CONTROLADOR DE USUARIOS

###CREAR USUARIO
POST https://aplicacion-de-tareas-spring-boot.onrender.com/api/usuarios/crearUsuario
Content-Type: application/json

{
  "nombre" : "Alice",
  "email" : "alice.m@gmail.com",
  "numeroWhatsapp" : "921420759",
  "contraseña" : "Alohomora19"
}

### ELIMINAR USUARIO
DELETE https://aplicacion-de-tareas-spring-boot.onrender.com/api/usuarios/eliminarUsuario/2
Content-Type: application/json

### LOGIN USUARIO
POST https://aplicacion-de-tareas-spring-boot.onrender.com/api/usuarios/login
Content-Type: application/json

{
  "email": "alice.789m@gmail.com",
  "contraseña": "Alohomora19"
}

###CONTROLADOR DE TAREAS

###CREAR NUEVA TAREA
POST https://aplicacion-de-tareas-spring-boot.onrender.com/api/tareas/crearTarea/8
Content-Type: application/json

{
  "titulo": "Esta tarea trata sobre programacion",
  "descripcion": "El dia lunes debemos jugar muchos videojuegos de verdaa",
  "recordatorio": "2025-12-12 17:37",
  "estadoTarea": false
}

###ACTUALIZAR TAREA
PUT https://aplicacion-de-tareas-spring-boot.onrender.com/api/tareas/actualizarTarea/8/24
Content-Type: application/json

{
  "titulo": "putito",
  "descripcion": "Comprar leche, huevos y pan.",
  "recordatorio": "2025-12-31 09:52",
  "estadoTarea": true
}

###ELIMINAR TAREA
DELETE https://aplicacion-de-tareas-spring-boot.onrender.com/api/tareas/eliminarTarea/6/50
Content-Type: application/json

###LISTAR TAREAS DE UN USUARIO
GET https://aplicacion-de-tareas-spring-boot.onrender.com/api/tareas/listaTareas/8
Content-Type: application/json

###CONTROLADOR DE IA
GET https://aplicacion-de-tareas-spring-boot.onrender.com/api/ia/14
Content-Type: application/json

{
  "texto" : "¿que tareas tengo?"
}



###
# curl --request POST
#  --url https://apiwsp.factiliza.com/v1/message/sendtext/NTE5MTA5NTkyMzA%3D
#  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODg0MiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImNvbnN1bHRvciJ9.IhH9bpi5lvjDgflrvh1Ry5crQz-yMYBucUNsTfy6KRs'
#  --header 'Content-Type: application/json'
#  --data '
#{
#  "number": "51910959230",
#  "text": "PRUEBA DE NOTIFICACION DE TAREAS AUTOMATICAS"
#}
#'
POST https://apiwsp.factiliza.com/v1/message/sendtext/NTE5MjE0MjA3NTk=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODg0MiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImNvbnN1bHRvciJ9.IhH9bpi5lvjDgflrvh1Ry5crQz-yMYBucUNsTfy6KRs
Content-Type: application/json


{
  "number": "51921420759",
  "text": "PRUEBA DE NOTIFICACION DE TAREAS AUTOMATICAS"
}


###


